# Generated by Django 5.1 on 2024-09-04 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_resercation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resercation',
        ),
    ]
