version: '3.9'

services:
  web:
    build: ./airbnb_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./airbnb_backend/ :usr/src/airbnb_backend/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    